#! /bin/bash
# This is a list of dependency packages as listed on the lxqt wiki
# and adapted to Slackware package naming.
# This file is sourced by the CHECK_PREREQ.sh script in order to give suggestions
# in case some packages are not found.
#
# The list of suggestions is based on slackware64-current as of 25/04/2020 for
# official packages, alienbob's ktown repository for KDE5 specific packages and
# sbopkg for all the rest.

### NOTICE: gtk+2 and gtk+3 won't be recognized by CHECK_PREREQ.sh as installed
### 		even if they are, but this isn't a problem. I'll fix it later.

declare -A deps

deps+=(
	# buildenv
	["cmake"]="cmake-3.17.1-x86_64-1"
	["git"]="git-2.26.2-x86_64-1"
	# Qt5
	["qt5"]="qt5-5.13.2-x86_64-3"
	# KDE5
	["kguiaddons"]="kguiaddons-5.68.0-x86_64-1alien"
	["libkscreen"]="libkscreen2-5.18.3-x86_64-1alien"
	["kidletime"]="kidletime-5.68.0-x86_64-1alien"
	["kwindowsystem"]="kwindowsystem-5.68.0-x86_64-1alien"
	["solid"]="solid-5.68.0-x86_64-1alien"
	# Misc
	["libstatgrab"]="libstatgrab-0.92-x86_64-1danix"
	["alsa-lib"]="alsa-lib-1.2.2-x86_64-1"
	["pulseaudio"]="pulseaudio-13.0-x86_64-2"
	["lm_sensors"]="lm_sensors-3.6.0-x86_64-1"
	["libconfig"]="libconfig-1.7.2-x86_64-1danix"
	["muparser"]="muParser-2.2.5-x86_64-1danix"
	["upower"]="upower-0.9.23-x86_64-4"
	["polkit-qt5"]="polkit-qt5-1-0.113.0-x86_64-1alien"
	["sudo"]="sudo-1.8.31p1-x86_64-1_pam"
	["xmessage"]="xmessage-1.0.5-x86_64-2"
	["libXv"]="libXv-1.0.11-x86_64-2"
	["libxcursor"]="libXcursor-1.2.0-x86_64-1"
	["libxcomposite"]="libXcomposite-0.4.5-x86_64-1"
	["libxcb"]="libxcb-1.14-x86_64-1"
	["libxkbcommon"]="libxkbcommon-0.10.0-x86_64-2"
	["libdbusmenu-qt5"]="libdbusmenu-qt5-0.9.3+16.04.20160218-x86_64-1alien"
	["gtk+2"]="gtk+2-2.24.32-x86_64-3"
	["gtk+3"]="gtk+3-3.24.18-x86_64-2"
	["hicolor-icon-theme"]="hicolor-icon-theme-0.17-noarch-2"
	["xdg-utils"]="xdg-utils-1.1.3-noarch-2"
	["xdg-user-dirs"]="xdg-user-dirs-0.17-x86_64-1"
	["oxygen-icons"]="oxygen-icons5-5.68.0-noarch-1alien"
	["openbox"]="openbox-3.6.1-x86_64-1danix"
)
